
trigger:
 tags:
   include:
     - '*'
 branches:
   include:
     - '*'

jobs:
    - template: ./tools/azure-devops/azure-pipelines-win.yml
    - template: ./tools/azure-devops/azure-pipelines-dist.yml